baseURL = "https://yukemuli.dance"
theme = "lanyon-hugo"
languagecode = "ja-jp"
defaultcontentlanguage = "ja"

publishDir = "."
paginate = 20

buildFuture = true

[params]
title = "YUKEMULI"
tagLine = "= 風呂 × 音楽"
dateForm = "2006 / 01 / 02"
favicon = "/img/favicon.png"
custom_css = ["/css/main.css"]