baseURL = "https://yukemuli.dance"
theme = "lanyon-hugo"
languagecode = "ja-jp"
defaultcontentlanguage = "ja"

publishDir = "."
paginate = 20

buildFuture = true

[params]
title = "YUKEMULI"
tagLine = "= 風呂 × 音楽"